# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedData', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('hit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopfinder.SearchData')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopfinder.Shop')),
            ],
        ),
    ]
